name: CI
# If you update paths, make sure to update them in no-ci.yml as well
on:
    push:
      branches:
        - master
      paths-ignore:
        - .github/actions
        - "README.md"
    pull_request:
      paths-ignore:
        - .github/actions
        - "README.md"

permissions:
    contents: read

env:
    REPOSITORY: "gcr.io/helical-crowbar-220917"
    PROJECT_ID: "helical-crowbar-220917"
    PLATFORMS: "linux/amd64"
    prometheus_java_agent_version: 0.12.0
    PR_NUMBER: ${{ github.event.pull_request.number || github.ref_name }}
    NEXUS_USER: "jenkins"
    NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"

concurrency:
    group: ${{ github.workflow_ref }}
    cancel-in-progress: true

jobs:
    build-and-publish:
        name: Build libraries and image
        runs-on: ubuntu-latest
        steps:
            - name: Build w/ sbt
              uses: garnercorp/build-actions/scala@main
              with:
                maven-username: ${{ env.NEXUS_USER }}
                maven-password: ${{ env.NEXUS_PASSWORD }}
                copy-prometheus-to: lighthouse-jobs
                jars-to-simplify: lighthouse-jobs
                prometheus-url: https://nexus.garnercorp.com/repository/raw/jmx_prometheus_javaagent-${{ env.prometheus_java_agent_version }}.jar
                build-script: scripts/build-scala-ci.sh
                build-script-args: ${{ env.PR_NUMBER }}
                container-project: ${{ env.PROJECT_ID }}
                google-credentials-json: ${{ secrets.GCR_JSON_KEY }}
                google-cloud-sdk-version: ${{ vars.GCLOUD_SDK_VERSION }}

            - name: Build and Publish Jobs image
              uses: garnercorp/build-actions/image@main
              with:
                container-project: ${{ env.PROJECT_ID }}
                platforms: ${{ env.PLATFORMS }}
                working-directory: "lighthouse-jobs"
