name: gormorant CI
# If you update paths, make sure to update them in no-ci.yml as well
on:
  push:
    paths-ignore:
      - .github/actions
      - "README.md"
  pull_request:
    paths-ignore:
      - .github/actions
      - "README.md"

permissions:
  contents: read

env:
  REPOSITORY: "gcr.io/helical-crowbar-220917"
  PROJECT_ID: "helical-crowbar-220917"
  PLATFORMS: "linux/amd64"
  PR_NUMBER: ${{ github.event.pull_request.number || github.ref_name }}
  NEXUS_USER: "jenkins"
  NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Build w/ sbt
        if: github.ref_name != 'main'
        uses: garnercorp/build-actions/scala@main
        with:
          maven-username: ${{ env.NEXUS_USER }}
          maven-password: ${{ env.NEXUS_PASSWORD }}
          build-script: scripts/build-scala-ci.sh
          build-script-args: ${{ env.PR_NUMBER }}
          extra-sbt-args: test

      - name: Publish
        uses: garnercorp/build-actions/scala@main
        if: github.ref_name == 'main'
        with:
          maven-username: ${{ env.NEXUS_USER }}
          maven-password: ${{ env.NEXUS_PASSWORD }}
          build-script: scripts/build-scala-ci.sh
          build-script-args: ${{ env.PR_NUMBER }}
          extra-sbt-args: publish
